# Generated by Django 4.2.3 on 2023-09-05 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_certificate_certifying_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certifying_institution",
            field=models.ForeignKey(
                max_length=500,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="projects.certifyinginstitution",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="profiles",
            field=models.ManyToManyField(
                max_length=500,
                related_name="certificates",
                to="projects.profile",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, max_length=500),
        ),
    ]
